export const ADD_SERVICE = "ADD_SERVICE";
export const EDIT_SERVICE = "EDIT_SERVICE";
export const EDITING_SERVICE = "EDITING_SERVICE";
export const END_CHANGES_SERVICE = "END_CHANGES_SERVICE";
export const FORM_CHANGE_FIELD_SERVICE = "FORM_CHANGE_FIELD_SERVICE";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const SEARCH_CHANGE_FIELD_SERVICE = "SEARCH_CHANGE_FIELD_SERVICE";
